### ISSUE TITLE
Pool Display on Network page

### ISSUE THREAD

**Issue by Focus9** [de-luxe/burstcoin-observer#3]
Hi Luxe, a couple of quick questiojs.

WIth all the addition of new pools, is it possible that you pull the network status for the pools from the wallet like the pool page so that we don't have to add manually new pools when they are put online?

Also, when will the new version with the graphs be released?

**Comment by de-luxe** [comment]
@Focus9 No, the pool url is not within the blockchain, if e.g. every pool account would add it's url to account title or description it could be somehow parsed ... but without there is no chance to automate it.

Yes, i'm late with the last updates, sorry for that ... still have to make some hardcoded things adjustable to be able to release ... maybe this weekend i will find some time for doing that.

**Comment by de-luxe** [comment]
@Focus9 New version is available.
